
package schemas.dynamics.microsoft.page.productos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Productos_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", wsdlLocation = "http://localhost:7047/DynamicsNAV/WS/Page/Productos")
public class ProductosService
    extends Service
{

    private final static URL PRODUCTOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOSSERVICE_EXCEPTION;
    private final static QName PRODUCTOSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/productos", "Productos_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7047/DynamicsNAV/WS/Page/Productos");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOSSERVICE_WSDL_LOCATION = url;
        PRODUCTOSSERVICE_EXCEPTION = e;
    }

    public ProductosService() {
        super(__getWsdlLocation(), PRODUCTOSSERVICE_QNAME);
    }

    public ProductosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOSSERVICE_QNAME, features);
    }

    public ProductosService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOSSERVICE_QNAME);
    }

    public ProductosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOSSERVICE_QNAME, features);
    }

    public ProductosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductosPort
     */
    @WebEndpoint(name = "Productos_Port")
    public ProductosPort getProductosPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/productos", "Productos_Port"), ProductosPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductosPort
     */
    @WebEndpoint(name = "Productos_Port")
    public ProductosPort getProductosPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/productos", "Productos_Port"), ProductosPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOSSERVICE_EXCEPTION!= null) {
            throw PRODUCTOSSERVICE_EXCEPTION;
        }
        return PRODUCTOSSERVICE_WSDL_LOCATION;
    }

}
