
package schemas.dynamics.microsoft.nav.system;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SystemService", targetNamespace = "urn:microsoft-dynamics-schemas/nav/system/", wsdlLocation = "http://localhost:7047/DynamicsNAV/WS/SystemService")
public class SystemService
    extends Service
{

    private final static URL SYSTEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYSTEMSERVICE_EXCEPTION;
    private final static QName SYSTEMSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/nav/system/", "SystemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7047/DynamicsNAV/WS/SystemService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYSTEMSERVICE_WSDL_LOCATION = url;
        SYSTEMSERVICE_EXCEPTION = e;
    }

    public SystemService() {
        super(__getWsdlLocation(), SYSTEMSERVICE_QNAME);
    }

    public SystemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSTEMSERVICE_QNAME, features);
    }

    public SystemService(URL wsdlLocation) {
        super(wsdlLocation, SYSTEMSERVICE_QNAME);
    }

    public SystemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSTEMSERVICE_QNAME, features);
    }

    public SystemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SystemServicePort
     */
    @WebEndpoint(name = "SystemService_Port")
    public SystemServicePort getSystemServicePort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/nav/system/", "SystemService_Port"), SystemServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemServicePort
     */
    @WebEndpoint(name = "SystemService_Port")
    public SystemServicePort getSystemServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/nav/system/", "SystemService_Port"), SystemServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSTEMSERVICE_EXCEPTION!= null) {
            throw SYSTEMSERVICE_EXCEPTION;
        }
        return SYSTEMSERVICE_WSDL_LOCATION;
    }

}
