
package schemas.dynamics.microsoft.page.loginweblist;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginWebList_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginWebListPort {


    /**
     * 
     * @param no
     * @return
     *     returns schemas.dynamics.microsoft.page.loginweblist.LoginWebList
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/loginweblist:Read")
    @WebResult(name = "LoginWebList", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.ReadResult")
    public LoginWebList read(
        @WebParam(name = "no", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.loginweblist.LoginWebList
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/loginweblist:ReadByRecId")
    @WebResult(name = "LoginWebList", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.ReadByRecIdResult")
    public LoginWebList readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns schemas.dynamics.microsoft.page.loginweblist.LoginWebListList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/loginweblist:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.ReadMultipleResult")
    public LoginWebListList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        List<LoginWebListFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/loginweblist:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/loginweblist:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        String key);

    /**
     * 
     * @param loginWebList
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/loginweblist:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.CreateResult")
    public void create(
        @WebParam(name = "LoginWebList", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", mode = WebParam.Mode.INOUT)
        Holder<LoginWebList> loginWebList);

    /**
     * 
     * @param loginWebListList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/loginweblist:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "LoginWebList_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", mode = WebParam.Mode.INOUT)
        Holder<LoginWebListList> loginWebListList);

    /**
     * 
     * @param loginWebList
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/loginweblist:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.UpdateResult")
    public void update(
        @WebParam(name = "LoginWebList", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", mode = WebParam.Mode.INOUT)
        Holder<LoginWebList> loginWebList);

    /**
     * 
     * @param loginWebListList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/loginweblist:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "LoginWebList_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", mode = WebParam.Mode.INOUT)
        Holder<LoginWebListList> loginWebListList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/loginweblist:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", className = "schemas.dynamics.microsoft.page.loginweblist.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist")
        String key);

}
