
package schemas.dynamics.microsoft.page.loginweblist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginWebList_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/loginweblist", wsdlLocation = "http://localhost:7047/DynamicsNAV/WS/Page/LoginWebList")
public class LoginWebListService
    extends Service
{

    private final static URL LOGINWEBLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINWEBLISTSERVICE_EXCEPTION;
    private final static QName LOGINWEBLISTSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/loginweblist", "LoginWebList_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7047/DynamicsNAV/WS/Page/LoginWebList");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINWEBLISTSERVICE_WSDL_LOCATION = url;
        LOGINWEBLISTSERVICE_EXCEPTION = e;
    }

    public LoginWebListService() {
        super(__getWsdlLocation(), LOGINWEBLISTSERVICE_QNAME);
    }

    public LoginWebListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINWEBLISTSERVICE_QNAME, features);
    }

    public LoginWebListService(URL wsdlLocation) {
        super(wsdlLocation, LOGINWEBLISTSERVICE_QNAME);
    }

    public LoginWebListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINWEBLISTSERVICE_QNAME, features);
    }

    public LoginWebListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginWebListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginWebListPort
     */
    @WebEndpoint(name = "LoginWebList_Port")
    public LoginWebListPort getLoginWebListPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/loginweblist", "LoginWebList_Port"), LoginWebListPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginWebListPort
     */
    @WebEndpoint(name = "LoginWebList_Port")
    public LoginWebListPort getLoginWebListPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/loginweblist", "LoginWebList_Port"), LoginWebListPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINWEBLISTSERVICE_EXCEPTION!= null) {
            throw LOGINWEBLISTSERVICE_EXCEPTION;
        }
        return LOGINWEBLISTSERVICE_WSDL_LOCATION;
    }

}
