
package schemas.dynamics.microsoft.page.supplier;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Supplier_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SupplierPort {


    /**
     * 
     * @param no
     * @return
     *     returns schemas.dynamics.microsoft.page.supplier.Supplier
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/supplier:Read")
    @WebResult(name = "Supplier", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.ReadResult")
    public Supplier read(
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.supplier.Supplier
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/supplier:ReadByRecId")
    @WebResult(name = "Supplier", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.ReadByRecIdResult")
    public Supplier readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        String recId);

    /**
     * 
     * @param setSize
     * @param bookmarkKey
     * @param filter
     * @return
     *     returns schemas.dynamics.microsoft.page.supplier.SupplierList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/supplier:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.ReadMultipleResult")
    public SupplierList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        List<SupplierFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/supplier:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/supplier:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier", className = "schemas.dynamics.microsoft.page.supplier.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/supplier")
        String key);

}
