
package schemas.dynamics.microsoft.page.productos;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Productos_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductosPort {


    /**
     * 
     * @param no
     * @return
     *     returns schemas.dynamics.microsoft.page.productos.Productos
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/productos:Read")
    @WebResult(name = "Productos", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.ReadResult")
    public Productos read(
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.productos.Productos
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/productos:ReadByRecId")
    @WebResult(name = "Productos", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.ReadByRecIdResult")
    public Productos readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        String recId);

    /**
     * 
     * @param setSize
     * @param bookmarkKey
     * @param filter
     * @return
     *     returns schemas.dynamics.microsoft.page.productos.ProductosList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/productos:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.ReadMultipleResult")
    public ProductosList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        List<ProductosFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/productos:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/productos:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos", className = "schemas.dynamics.microsoft.page.productos.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/productos")
        String key);

}
