
package schemas.dynamics.microsoft.page.pedidoscompra;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PedidosCompra_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PedidosCompraPort {


    /**
     * 
     * @param no
     * @return
     *     returns schemas.dynamics.microsoft.page.pedidoscompra.PedidosCompra
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:Read")
    @WebResult(name = "PedidosCompra", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.ReadResult")
    public PedidosCompra read(
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.pedidoscompra.PedidosCompra
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:ReadByRecId")
    @WebResult(name = "PedidosCompra", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.ReadByRecIdResult")
    public PedidosCompra readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns schemas.dynamics.microsoft.page.pedidoscompra.PedidosCompraList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.ReadMultipleResult")
    public PedidosCompraList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        List<PedidosCompraFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String key);

    /**
     * 
     * @param pedidosCompra
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.CreateResult")
    public void create(
        @WebParam(name = "PedidosCompra", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", mode = WebParam.Mode.INOUT)
        Holder<PedidosCompra> pedidosCompra);

    /**
     * 
     * @param pedidosCompraList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "PedidosCompra_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", mode = WebParam.Mode.INOUT)
        Holder<PedidosCompraList> pedidosCompraList);

    /**
     * 
     * @param pedidosCompra
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.UpdateResult")
    public void update(
        @WebParam(name = "PedidosCompra", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", mode = WebParam.Mode.INOUT)
        Holder<PedidosCompra> pedidosCompra);

    /**
     * 
     * @param pedidosCompraList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "PedidosCompra_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", mode = WebParam.Mode.INOUT)
        Holder<PedidosCompraList> pedidosCompraList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String key);

    /**
     * 
     * @param purchLinesKey
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete_PurchLines", action = "urn:microsoft-dynamics-schemas/page/pedidoscompra:Delete_PurchLines")
    @WebResult(name = "Delete_PurchLines_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
    @RequestWrapper(localName = "Delete_PurchLines", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.DeletePurchLines")
    @ResponseWrapper(localName = "Delete_PurchLines_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra", className = "schemas.dynamics.microsoft.page.pedidoscompra.DeletePurchLinesResult")
    public boolean deletePurchLines(
        @WebParam(name = "PurchLines_Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/pedidoscompra")
        String purchLinesKey);

}
