
package schemas.dynamics.microsoft.page.orderinformation;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderInformation_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderInformationPort {


    /**
     * 
     * @param documentNo
     * @return
     *     returns schemas.dynamics.microsoft.page.orderinformation.OrderInformation
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/orderinformation:Read")
    @WebResult(name = "OrderInformation", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.ReadResult")
    public OrderInformation read(
        @WebParam(name = "Document_No", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        String documentNo);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.orderinformation.OrderInformation
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/orderinformation:ReadByRecId")
    @WebResult(name = "OrderInformation", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.ReadByRecIdResult")
    public OrderInformation readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        String recId);

    /**
     * 
     * @param setSize
     * @param bookmarkKey
     * @param filter
     * @return
     *     returns schemas.dynamics.microsoft.page.orderinformation.OrderInformationList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/orderinformation:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.ReadMultipleResult")
    public OrderInformationList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        List<OrderInformationFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/orderinformation:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/orderinformation:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", className = "schemas.dynamics.microsoft.page.orderinformation.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation")
        String key);

}
