
package schemas.dynamics.microsoft.page.orderinformation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderInformation_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/orderinformation", wsdlLocation = "http://localhost:7047/DynamicsNAV/WS/Page/OrderInformation")
public class OrderInformationService
    extends Service
{

    private final static URL ORDERINFORMATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERINFORMATIONSERVICE_EXCEPTION;
    private final static QName ORDERINFORMATIONSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/orderinformation", "OrderInformation_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7047/DynamicsNAV/WS/Page/OrderInformation");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERINFORMATIONSERVICE_WSDL_LOCATION = url;
        ORDERINFORMATIONSERVICE_EXCEPTION = e;
    }

    public OrderInformationService() {
        super(__getWsdlLocation(), ORDERINFORMATIONSERVICE_QNAME);
    }

    public OrderInformationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERINFORMATIONSERVICE_QNAME, features);
    }

    public OrderInformationService(URL wsdlLocation) {
        super(wsdlLocation, ORDERINFORMATIONSERVICE_QNAME);
    }

    public OrderInformationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERINFORMATIONSERVICE_QNAME, features);
    }

    public OrderInformationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderInformationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderInformationPort
     */
    @WebEndpoint(name = "OrderInformation_Port")
    public OrderInformationPort getOrderInformationPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/orderinformation", "OrderInformation_Port"), OrderInformationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderInformationPort
     */
    @WebEndpoint(name = "OrderInformation_Port")
    public OrderInformationPort getOrderInformationPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/orderinformation", "OrderInformation_Port"), OrderInformationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERINFORMATIONSERVICE_EXCEPTION!= null) {
            throw ORDERINFORMATIONSERVICE_EXCEPTION;
        }
        return ORDERINFORMATIONSERVICE_WSDL_LOCATION;
    }

}
