
package schemas.dynamics.microsoft.codeunit.serienextid;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serieNextId_Port", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/serieNextId")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SerieNextIdPort {


    /**
     * 
     * @param noSeriesCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetNextNoSerie", action = "urn:microsoft-dynamics-schemas/codeunit/serieNextId:GetNextNoSerie")
    @WebResult(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/serieNextId")
    @RequestWrapper(localName = "GetNextNoSerie", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/serieNextId", className = "schemas.dynamics.microsoft.codeunit.serienextid.GetNextNoSerie")
    @ResponseWrapper(localName = "GetNextNoSerie_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/serieNextId", className = "schemas.dynamics.microsoft.codeunit.serienextid.GetNextNoSerieResult")
    public String getNextNoSerie(
        @WebParam(name = "noSeriesCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/serieNextId")
        String noSeriesCode);

}
