
package schemas.dynamics.microsoft.page.proveedor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proveedor_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/proveedor", wsdlLocation = "http://localhost:7047/DynamicsNAV/WS/Page/Proveedor")
public class ProveedorService
    extends Service
{

    private final static URL PROVEEDORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVEEDORSERVICE_EXCEPTION;
    private final static QName PROVEEDORSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/proveedor", "Proveedor_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7047/DynamicsNAV/WS/Page/Proveedor");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVEEDORSERVICE_WSDL_LOCATION = url;
        PROVEEDORSERVICE_EXCEPTION = e;
    }

    public ProveedorService() {
        super(__getWsdlLocation(), PROVEEDORSERVICE_QNAME);
    }

    public ProveedorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVEEDORSERVICE_QNAME, features);
    }

    public ProveedorService(URL wsdlLocation) {
        super(wsdlLocation, PROVEEDORSERVICE_QNAME);
    }

    public ProveedorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVEEDORSERVICE_QNAME, features);
    }

    public ProveedorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProveedorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProveedorPort
     */
    @WebEndpoint(name = "Proveedor_Port")
    public ProveedorPort getProveedorPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/proveedor", "Proveedor_Port"), ProveedorPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProveedorPort
     */
    @WebEndpoint(name = "Proveedor_Port")
    public ProveedorPort getProveedorPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/proveedor", "Proveedor_Port"), ProveedorPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVEEDORSERVICE_EXCEPTION!= null) {
            throw PROVEEDORSERVICE_EXCEPTION;
        }
        return PROVEEDORSERVICE_WSDL_LOCATION;
    }

}
