
package schemas.dynamics.microsoft.page.purchaseorder;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrder_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseOrderPort {


    /**
     * 
     * @param documentNo
     * @return
     *     returns schemas.dynamics.microsoft.page.purchaseorder.PurchaseOrder
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/purchaseorder:Read")
    @WebResult(name = "PurchaseOrder", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.ReadResult")
    public PurchaseOrder read(
        @WebParam(name = "Document_No", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        String documentNo);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.purchaseorder.PurchaseOrder
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/purchaseorder:ReadByRecId")
    @WebResult(name = "PurchaseOrder", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.ReadByRecIdResult")
    public PurchaseOrder readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        String recId);

    /**
     * 
     * @param setSize
     * @param bookmarkKey
     * @param filter
     * @return
     *     returns schemas.dynamics.microsoft.page.purchaseorder.PurchaseOrderList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/purchaseorder:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.ReadMultipleResult")
    public PurchaseOrderList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        List<PurchaseOrderFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/purchaseorder:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/purchaseorder:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", className = "schemas.dynamics.microsoft.page.purchaseorder.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder")
        String key);

}
