
package schemas.dynamics.microsoft.page.purchaseorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrder_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/purchaseorder", wsdlLocation = "http://localhost:7047/DynamicsNAV/WS/Page/PurchaseOrder")
public class PurchaseOrderService
    extends Service
{

    private final static URL PURCHASEORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERSERVICE_EXCEPTION;
    private final static QName PURCHASEORDERSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/purchaseorder", "PurchaseOrder_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7047/DynamicsNAV/WS/Page/PurchaseOrder");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERSERVICE_WSDL_LOCATION = url;
        PURCHASEORDERSERVICE_EXCEPTION = e;
    }

    public PurchaseOrderService() {
        super(__getWsdlLocation(), PURCHASEORDERSERVICE_QNAME);
    }

    public PurchaseOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERSERVICE_QNAME, features);
    }

    public PurchaseOrderService(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERSERVICE_QNAME);
    }

    public PurchaseOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERSERVICE_QNAME, features);
    }

    public PurchaseOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrderPort
     */
    @WebEndpoint(name = "PurchaseOrder_Port")
    public PurchaseOrderPort getPurchaseOrderPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/purchaseorder", "PurchaseOrder_Port"), PurchaseOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrderPort
     */
    @WebEndpoint(name = "PurchaseOrder_Port")
    public PurchaseOrderPort getPurchaseOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/purchaseorder", "PurchaseOrder_Port"), PurchaseOrderPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERSERVICE_EXCEPTION!= null) {
            throw PURCHASEORDERSERVICE_EXCEPTION;
        }
        return PURCHASEORDERSERVICE_WSDL_LOCATION;
    }

}
